---
title: "Using the Rvoteview API"
author: "Luke Sonnet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This package provides tools to query and download from the VoteView database. This vignette will demonstrate the different types of queries that can be used, how `rvoteview` can be used to do ideal point estimation on a subset of votes using the `pscl` package, and how `rvoteview` facilitates regression analyses of congressional voting behavior.

# Installation

To install this package, ensure you have `devtools` installed. If you do not, run `install.packages("devtools")` and then install from GitHub using

```R
devtools::install_github("JeffreyBLewis/Rvoteview")
```

# Querying the database

Using a custom query parser, we allow both simple and complex queries to be made to the VoteView datase...

# Downloading rollcall data

How to download...

# Two example usages

## Ideal point estimation using `pscl`

## Regression analysis of roll call behavior

# Additional tools

# References